apiVersion: v1
kind: Pod
metadata:
  name: sidecar-forward-proxy
spec:
  containers:
  - name: nginx
    image: vadimeisenbergibm/nginx-forward-proxy
  - name: envoy
    image: vadimeisenbergibm/envoy-sidecar-forward-proxy
    securityContext:
      privileged: true
